name: CICD integrations

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: Demo

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test with Maven
      run: mvn clean test

  archive-test-results:
    needs: build
    runs-on: Demo
    if: always()  # This ensures the job runs even if 'build' fails
    steps:
    - name: Archive Test Results
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: ./ExtentReports/
